### ISSUE TITLE
bug: console messages display translation string

### ISSUE THREAD

**Issue by mikkauwu** [adibarra/enchant-tweaker#11]
### What happened?

When only enchant-tweaker and fabric api are installed, chat messages will display in the console as `chat.type.text/chat.display.admin/chat.display.announcement` etc., preparing spawn displays as `menu.preparingSpawn`, and advancements as e.g. `advancements.story.mine_stone.description`.

### What should have happened?

I expected to see the translated chat messages, spawn preparing messages, and advancements

### How to reproduce?

1. Install enchant-tweaker on a Fabric 1.20.1 server (+ fabric-api)
2. Start server. When loading spawn, a bunch of `menu.preparingSpawn` messages are displayed instead of "Preparing spawn area: 0%"
3. Use command `say test` in console, "chat.type.announcement" is displayed instead of "[Server] test"
4. Use any command e.g. `op mikkauwu`, "commands.op.success" is displayed
5. Talk in-game, messages will appear in console as "chat.type.text" instead of the actual message

### What is the jar file name?

enchanttweaker-1.4.3+mc1.20-1.20.1.jar

### What Minecraft version?

Fabric 1.20.1

### Any relevant logs?

https://mclo.gs/iosCGTT

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, unfortunately as far as I'm aware this seems to be a bug with MC in general. (Happens even with vanilla servers). It seems to be a somewhat rare bug though. I would recommend restarting the server until it works or perhaps recreating the server with the same world and config as it seems to be caused by missing translation files. You may be able to manually copy them over from a fresh install.

If you are able to replicate this consistently with a fresh install and EnchantTweaker please reopen the issue. Thanks!

**Comment by mikkauwu** [comment]
Hi, thank you for the response. This was happening in my main server so I individually tested all the mods, and removing EnchantTweaker fixed the problem. I created a completely fresh fabric server install to test with only EnchantTweaker +default config, and I had the same issue, which is why I thought it might be a problem with EnchantTweaker.

**Comment by adibarra** [comment]
Perfect. I'll start looking into fixing the issue then. Thanks for the report!

**Comment by adibarra** [comment]
Should be fixed now. It'll be included in the next update (v1.4.4).
