### ISSUE TITLE
bug: Not Too Expensive not working at all.

### ISSUE THREAD

**Issue by caesarakalaeii** [adibarra/enchant-tweaker#12]
### What happened?

Enabled "Not Too Expensive"
Enchantment with 60 Levels is still too expensive, even though the player having 80 levels.

### What should have happened?

Enchantment with 60 levels should be applied.

### How to reproduce?

Install the mod.
Modify the config, turning everything off, except mod_enabled, cheap_names and not_too_expensive.
Get Book, normally being too Expensive.
Try to enchant.

### What is the jar file name?

enchanttweaker-1.4.3+mc1.20-1.20.1

### What Minecraft version?

Fabric 1.20.1

### Any relevant logs?

https://mclo.gs/4dTxH1l
As you can see, no errors will be displayed.
This is the config file:
https://mclo.gs/GVfuiOy

### Anything else?

The only other mod installed is the Fabric API, while in issue #10 It states it is a problem with Fabrication. This obviously isn't the case here.

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
I can't seem to be able to reproduce this but just to make sure, does the client have the same config file as the server? It currently does not sync on server join and simply uses the clients config. In this case, the UI may say 'Too Expensive' but it should still let you pull it out after combining it.

If this isn't the case, can you expand on your reproduction instructions? Including the exact enchantments you were trying to combine may be helpful. Thanks.

**Comment by caesarakalaeii** [comment]
The Client doesn't have the mod installed at all.
I was under the assumption that the client install was completely optional and thus not needed for most functionalities.

**Comment by adibarra** [comment]
As it happens, one of the two tweaks requiring the client-side mod is the "Not Too Expensive" tweak. This is because it needs to hide the "Too Expensive!" text client-side. The other tweak is the "Shiny Names" one for a similar reason. That said, even without the mod, it should still let you pull the items out of the anvil (as long as you have enough levels). However, you would be unable to see the level cost due to the "Too Expensive!" text, making it a bit of a guessing game.

Anyway, I'll add a section to the readme/description clarifying which tweaks require the client-side installation.
