### ISSUE TITLE
bug: Config not saving

### ISSUE THREAD

**Issue by alexzander700** [adibarra/enchant-tweaker#24]
### What happened?

I have a Prot 3 chestplate that I'm adding Prot 3 to, should give me Prot 4, but doesn't.
![image](https://github.com/adibarra/enchant-tweaker/assets/51793351/e8ebe5ea-dda0-4dd6-a482-3c02053d87be)
![image](https://github.com/adibarra/enchant-tweaker/assets/51793351/448588f8-6f92-4292-85ea-83dc60050bc1)

With further testing it seems to affect the entire mod, not just prot 3.

### What should have happened?

Should give Prot 4 when 3 + 3 is combined

### How to reproduce?

Using the listed version below on a Fabric server, none of the mods functions.... function.

### What is the jar file name?

enchanttweaker-1.4.7+mc1.20.3-1.20.4.jar

### What Minecraft version?

Fabric 1.20.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by alexzander700** [comment]
![image](https://github.com/adibarra/enchant-tweaker/assets/51793351/f6e140b3-0666-4940-bdaa-352aa40fa178)
The different prots seem to work in addition to each other, so some functionality is here, however I cannot go above vanilla limits

**Comment by alexzander700** [comment]
![image](https://github.com/adibarra/enchant-tweaker/assets/51793351/fdeeb051-eb7a-48bc-b54d-8e6d7aa00355)
And the axe enchants function as intended

**Comment by alexzander700** [comment]
The no_soul_speed_backlash does function as intended

**Comment by adibarra** [comment]
Hello, thanks for the report!
Could you attach a copy of your `enchant-tweaker.properties` config file and a list of any mods you are currently using.
I think it would be very helpful in this case. I'll start looking into the issue as soon as you do.

**Comment by alexzander700** [comment]
Alright, I shut down the server, changed the config, then started the server again and suddenly it works. Seeing as there was an in-game reload command, I thought that would allow for anything that was changed to apply (excluding mixins), but I guess not.

The bug is no longer that it doesn't work, but now that the config doesn't get changed via the in-game commands

**Comment by adibarra** [comment]
I see where the confusion comes from.

Every setting in the config that takes a `true/false` value requires a server restart to take effect. This is because the mod only loads the enabled 'tweaks' on startup (to prevent incompatibility issues). So to enable an unloaded 'tweak', you need to restart.

Additionally, the `/et reload` command is used for making changes to the config file while the game is running. Again, same issue here, any settings with `true/false` values still require a server restart. I'll update the `Enabling/Disabling mixins requires a restart to take effect` message to a more straightforward `This change requires a restart to take effect`.

And finally, there was indeed a bug with the `/et reload` command. Which wiped out any changes to the config file. This will be addressed in the next update (v1.4.8). 

Let me know if you still have any issues with the mod!
